# Generated by Django 3.0.4 on 2020-03-25 16:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('balance', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=500)),
                ('connection_date', models.DateTimeField(default=datetime.datetime(2020, 3, 25, 16, 13, 55, 852829, tzinfo=utc))),
                ('phone_no', models.IntegerField()),
                ('status', models.CharField(choices=[('S', 'Suspended'), ('O', 'Overdue'), ('A', 'Active'), ('D', 'Deactive')], max_length=1)),
                ('user_type', models.CharField(choices=[('A', 'admin'), ('G', 'general'), ('V', 'vip')], max_length=1)),
            ],
        ),
    ]
