# Generated by Django 3.0.4 on 2020-03-25 16:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0003_auto_20200325_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='price',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='connection_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 16, 40, 46, 968005, tzinfo=utc)),
        ),
    ]
