# Generated by Django 3.0.4 on 2020-03-25 17:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0007_auto_20200325_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='Date_issued',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 17, 15, 40, 588385, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='invoices',
            name='month',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='connection_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 17, 15, 40, 537521, tzinfo=utc)),
        ),
    ]
