# Generated by Django 3.0.4 on 2020-03-25 17:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0009_auto_20200325_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='payment_type',
            field=models.CharField(choices=[('B', 'Bkash'), ('C', 'Credit_Card'), ('D', 'cash_on_delivery')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='Date_issued',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 17, 19, 52, 271616, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='date_auto_disconnect',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 17, 19, 52, 271616, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='connection_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 17, 19, 52, 221723, tzinfo=utc)),
        ),
    ]
