# Generated by Django 3.0.4 on 2020-03-25 21:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0011_auto_20200326_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='package',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='isp.Packages'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='Date_issued',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 21, 24, 14, 944250, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='date_auto_disconnect',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 21, 24, 14, 944250, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='connection_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 21, 24, 14, 943252, tzinfo=utc)),
        ),
    ]
