# Generated by Django 3.2.4 on 2021-06-13 11:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0025_auto_20200326_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='Date_issued',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 11, 30, 1, 729391, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='date_auto_disconnect',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 11, 30, 1, 729391, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packages',
            name='price',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='connection_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 11, 30, 1, 664564, tzinfo=utc)),
        ),
    ]
